### ISSUE TITLE
Image turns black after multiple edits on windows with chromium

### ISSUE THREAD

**Issue by yuzhou-elation** [scaleflex/filerobot-image-editor#347] opened 2023-06-12 19:27 UTC
We've been seeing some issues when we edit the image multiple times, and the image turns black. For context, this is only occurring on windows with chromium (seen this issue on both chrome and edge). Firefox on windows in fine, and all browsers on mac are fine.

After our investigation, we believe we've sourced the issue to a memory leak in `getTransformedImgData` where references to react-konva canvases were being held onto, causing the GPU to run out of memory. This is evident as well by the fact that we when run into the issue, the entire browser turns black for a few seconds as well.

**Comment by AhmeeedMostafa** [comment] 2023-09-11 11:08
Hello @yuzhou-elation such an issue haven't noticed before form our side, so if u could provide more details about the device used and its specifications including ur debugging/checked info u had would be pretty useful and would make it quicker for us to fix that,
also u could fix it from ur side and create a PR for it would be fine if u already knew the issue .

**Comment by matheen821** [comment] 2023-09-12 07:21
we have also facing same, previously raised here

https://github.com/scaleflex/filerobot-image-editor/issues/293

**Comment by AhmeeedMostafa** [comment] 2023-09-12 07:41
@matheen821 as mentioned I couldn't reproduce it, which is hard for us to consider if we couldn't find the issue , so whether in that mentioned issue or for the current issue no useful context for producing.

We would appreciate if u could add some context and codesandbox produces ur issue

**Comment by matheen821** [comment] 2023-09-14 07:44
are you testing on Windows OS chrome browser?

**Comment by AhmeeedMostafa** [comment] 2023-09-14 08:03
@matheen821 yes we are checking it on chrome & windows OS but no issues,
And the screenshot you have provided doesn't seem related to the image editor's demo.

So again I'd appreciate adding more context.

**Comment by matheen821** [comment] 2023-09-14 08:38
sure below are the details and steps

It reproducible in 
OS: **Windows 10, windows 11** 
Browsers: Google Chrome, Edge
RAM Size: 6GB, 8GB

Steps:

1. Select an image with high quality like more than **15 MB to 25 MB**  to edit
2. edit the brightness or select the filter and save it 
3. Repeat the same Step 1 and Step 2 for more than 10 to 25 times, you will get below error or page will crash

<img width="1303" alt="Screenshot 2023-09-14 at 1 35 46 PM" src="https://github.com/scaleflex/filerobot-image-editor/assets/10617088/748767d2-ac48-4cbd-b943-c42d5cbf3cd0">

![IMG_6598 (1)](https://github.com/scaleflex/filerobot-image-editor/assets/10617088/09c61e22-f746-49af-84bf-82dff8cadb86)

**Comment by AhmeeedMostafa** [comment] 2023-09-26 13:06
Hey all, once we'll have a check once we have time if we produced the issue we will consider a fix for it.

**Comment by matheen821** [comment] 2023-09-27 07:07
Thank you, @AhmeeedMostafa, for your help. Please let us know if you require additional information.

**Comment by matheen821** [comment] 2023-10-16 14:01
Hi @AhmeeedMostafa , 

I hope you're doing well. we just wanted to follow up on the status of this issue. We understand that you have a lot on your plate, and we appreciate your help with this. If there's any additional information or assistance you need from our side, please let us know.

Thank you for your support!

**Comment by matheen821** [comment] 2023-11-13 16:16
Hi @AhmeeedMostafa ,

wanted to follow up on the status of this issue. can you please provide if any update on this.

Thank you!

**Comment by matheen821** [comment] 2023-11-14 10:25
@yuzhou-elation did you find any solution?

**Comment by AhmeeedMostafa** [comment] 2023-11-14 14:01
@matheen821 no time yet to check it, if you could debug it on the project and make a PR we will consider that for sure

**Comment by lukacavic** [comment] 2024-02-16 09:47
Hello, any changes on this?

**Comment by PedroMFernandes** [comment] 2024-04-02 18:10
@yuzhou-elation @matheen821 @AhmeeedMostafa. Hello, have you been able to find a solution to this issue? I'm currently experiencing the same.

**Comment by brunoalexsantos** [comment] 2024-04-02 22:54
Every time that we call the function getCurrentImgData the memory increase... The are any solution?

**Comment by brunoalexsantos** [comment] 2024-04-19 00:24
@matheen821 did you found a solution?

**Comment by AhmeeedMostafa** [comment] 2024-05-14 21:56
Hello, the issue is considered in the latest released minor version v4.8.0, please update the plugin and re-open the issue if there is any update.

**Closed by AhmeeedMostafa** 2024-05-14 21:56 UTC
Labels: Released
