### ISSUE TITLE
The watermark function causes page lag！！

### ISSUE THREAD

**Issue by DU0427** [scaleflex/filerobot-image-editor#502] opened 2024-11-20 02:58 UTC
After I switched to the watermark function on your demo page, the entire page froze. I integrated Vue into my own project and it was the same.

**Comment by kaplun07** [comment] 2024-12-08 20:25
I have the same problem ((

**Comment by rostagnolisandro** [comment] 2024-12-10 01:31
Hey there, I've just posted an issue (https://github.com/scaleflex/filerobot-image-editor/issues/514) and then I've found this one, I think they are related to the same bug, but I can't figure out what's the problem. It has something to do with buttons that show a list of options when clicked (like "Add watermark" button and "Save as" button).

**Comment by AhmeeedMostafa** [comment] 2024-12-30 10:06
Hey @DU0427  @kaplun07 the issue is fixed in v4.9.1 please check.

**Closed by AhmeeedMostafa** 2024-12-30 10:06 UTC
Labels: bug, Waiting release
