### ISSUE TITLE
Some pictures become empty when they are reset

### ISSUE THREAD

**Issue by xz333221** [scaleflex/filerobot-image-editor#141] opened 2021-11-01 07:27 UTC
After some pictures are opened, directly clicking the reset button will cause the current picture to disappear

**Comment by xz333221** [comment] 2021-11-01 07:32
The image address of the test is https://api.filerobot.com/scaleflex-tests-v5a/v3/get/e506e32e-56c1-57f5-a79c-f800b5750000

**Comment by xz333221** [comment] 2021-11-01 07:36
![image](https://user-images.githubusercontent.com/31299756/139637460-b7165433-cd81-4ad0-8745-f774447a4268.png)

**Comment by AhmeeedMostafa** [comment] 2021-11-16 16:04
Hey @xz333221 sorry for late reply, this is fixed in the new upcoming version , better to wait for it

**Comment by alexsatellite** [comment] 2021-11-18 17:15
Hello same issue,, when will be released the fix?

**Comment by equinox0** [comment] 2021-12-07 08:10
Hey, same issue.  
When the new version will be released?

**Comment by AhmeeedMostafa** [comment] 2021-12-07 15:10
@alexsatellite @equinox0 The issue is fixed in the new version it's now in BETA you could try it here [v4 branch](https://github.com/scaleflex/filerobot-image-editor/tree/v4)

**Closed** 2021-12-07 15:25 UTC

**Comment by narendraCloudester** [comment] 2022-02-15 09:00
We are facing the same issue "After some pictures are opened, directly clicking the reset button will cause the current picture to disappear" as we have used the LTS version [v3.12.16]  someone any idea how to disable the reset button or whole footer bcz version 4 is a beta version.?

**Comment by AhmeeedMostafa** [comment] 2022-02-15 14:05
@narendraCloudester as workaround u could use css to do that `div[title="Reset"] { display: none; }`
also u could give it a try for v4, it's in BETA but it'll go to prod very very soon as it becomes more mature now

**Comment by narendraCloudester** [comment] 2022-02-21 11:33
@AhmeeedMostafa  any idea about the future version will impact on the current version or it will be stable.

**Comment by AhmeeedMostafa** [comment] 2022-02-21 12:52
@narendraCloudester if you mean by the future version (v4) and current version (v3) then yes it'll impact as different configurations and initialization will be there

If u mean current version (current v4 beta release) and future version (prod. V4 release) almost will be stable but not sure if we faced/needed to change anything before going to prod. We'll
