### ISSUE TITLE
React component goes blank after opening and closing a modal with the component inside.

### ISSUE THREAD

**Issue by QuaCode** [scaleflex/filerobot-image-editor#251] opened 2022-08-15 18:00 UTC
It doesn't matter if you pass your source url as a prop or place the string directly. After doing conditional rendering a few times, the editor will open with a blank canvas.

import FilerobotImageEditor, { TABS } from 'react-filerobot-image-editor';

<FilerobotImageEditor
            savingPixelRatio={4}
            previewPixelRatio={window.devicePixelRatio}
            source={imageToEdit}
            onSave={editedImageObject => {
              if (!editedImageObject.imageBase64) return;
              console.log(editedImageObject.imageBase64);
            }}
            onClose={onCancel}
            Text={{
              fontSize: 16,
            }}
            Crop={{
              minWidth: 14,
              minHeight: 14,
              maxWidth: null,
              maxHeight: null,
              ratio: 'original',
              ratioTitleKey: 'Cortar',
              noPresets: false,
              autoResize: false,
              presetsItems: [],
              presetsFolders: [],
            }}
            Pen={{
              strokeWidth: 5,
            }}
            tabsIds={[TABS.ADJUST, TABS.ANNOTATE, TABS.FINETUNE]}
            defaultTabId={TABS.ADJUST}
          />

**Comment by rogeriochaves** [comment] 2022-08-20 21:12
same problem here

**Comment by rogeriochaves** [comment] 2022-08-20 21:13
same problem here

<img width="1017" alt="image" src="https://user-images.githubusercontent.com/792201/185766166-df18ea0c-bd72-4efa-98e9-80be1e2d1e20.png">

**Comment by TeoSymphonia** [comment] 2022-09-06 07:44
same problem

**Comment by SaraZoarob** [comment] 2022-10-01 19:03
hello @QuaCode and @TeoSymphonia, we are going to check and update you

**Comment by IdoiaReina** [comment] 2022-10-12 14:49
Same problem here, sometimes reloading one or several times the page makes it work again

**Comment by AhmeeedMostafa** [comment] 2023-02-10 18:27
The issue is fixed in version 4.3.8, please re-check it and let us know if all is good.

**Comment by zoranlj** [comment] 2023-03-07 17:08
Hi everyone, I have version `4.3.8`, and I'm still able to reproduce this error.
It happens randomly.
Not sure what causes it, but I'll give more information on my findings.
On Android, Chrome, Safari all is looking good. Issue is on iOS side.
Ionic and Capacitor uses [WKWebView](https://developer.apple.com/documentation/webkit/wkwebview) for iOS.
You can think of WKWebView as a stripped-down version of Safari.

### Stack

"@capacitor/core": "4.6.1",
"@capacitor/android": "4.6.1",
"@capacitor/ios": "4.6.1",
"@ionic/core": "6.4.1",
"@ionic/react": "6.4.1",
"react": "18.0.0",
"filerobot-image-editor": "4.3.8"

### Usage

Inside of an modal I'm conditional rendering `FilerobotImageEditor` component.

https://user-images.githubusercontent.com/6654464/223496208-f81b62ae-2660-4714-b798-e57f8371ce61.mov

**Comment by AhmeeedMostafa** [comment] 2023-03-07 17:28
@zoranlj I checked the video you have attached, it doesn't seem like an issue ur provided image hasn't loaded and there is an error generated (the pop-up shown) which is logical.

**Comment by zoranlj** [comment] 2023-03-08 12:53
@AhmeeedMostafa 

What am I doing wrong?

```
const editedImage = useRef<getCurrentImgDataFunction>();
const imageData = editedImage?.current?.({}).imageData;
console.log(imageData?.imageBase64);
```

Sometime output from the console is ok.
Like this: 
`data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABbsAAAPOCAYAAAAmwMXHAAAAAXNSR0IAr....`

Sometimes output from the console is not OK. 
Like this: 
`data:,`

**Comment by AhmeeedMostafa** [comment] 2023-03-29 23:20
@zoranlj  sorry for late reply, it is not appropriate to have an empty output from the plugin, so please create a new issue with ur production steps and codesandbox for ur code to check the issue

**Comment by josec0609** [comment] 2023-05-19 00:39
@AhmeeedMostafa
I can validate I'm seeing the exact same issue using react and only seeing issue on iOS devices. 
Seems like  `getCurrentImgDataFnRef` can sometimes returns bad output `data:,`. Not sure yet what's occurring, but have only had success recreating this issue on iOS devices (no luck on android or desktop browser) :( 

@zoranlj Were you able to resolve this issue?

**Comment by zoranlj** [comment] 2023-05-19 09:40
@josec0609 Try setting `savingPixelRatio={1}`. Also try to play around with that parameter to see what is best for you.

**Comment by josec0609** [comment] 2023-05-22 20:55
@zoranlj Thanks for the suggestion. Started playing around with savingPixelRatio, but it doesn't seem like setting it to any value solves the issue.

**Comment by josec0609** [comment] 2023-05-24 21:17
@AhmeeedMostafa I created sandbox to recreate the issue shown by @zoranlj above and what I would assume is the same root cause for issue reported by @QuaCode. [sandbox url](https://codesandbox.io/s/react-image-editor-filerobot-3gq4e2) 

Browser implementation differs but on Safari and iOS the issue is more prevalent. To recreate issue you need to visit sandbox on Safari or on iOS and edit/save image a few times. You will eventually get the following warning on console 
![Screenshot from iOS device output via remote inspector](https://github.com/scaleflex/filerobot-image-editor/assets/5415363/57de0199-858b-43c4-bb20-2b64e1f8ad42) If using Safari inspector, you can also see all the canvas elements still in browser memory via the Graphics tab. I believe if the maximum canvas memory is exceeded this can lead to `filerobot-image-editor` loading the editor with a blank image on subsequent requests to open image editor. 

The issue is related to how canvas elements are garbage collected by Safari.  [Article on Safari canvas elements](https://pqina.nl/blog/total-canvas-memory-use-exceeds-the-maximum-limit/#:~:text=It's%20limited%20to%20384MB%20on,of%20memory%20a%20canvas%20requires)

This cannot be fixed from the consumer side since we don't have references to all the canvas elements created by `file-robot-image-editor`. In the sandbox, I've tried to solve the issue myself, by trying to "manually release" the canvas elements created by the editor, but this only works for the canvas elements that are exposed, if end user uses the image editor enough times the issue will eventually pop up.

Related reference issue seen by others creating projects using Konva: https://github.com/konvajs/konva/issues/571

**Comment by HimonRana** [comment] 2023-10-12 15:11
This is still happening and i get same error as @josec0609, after taking a picture with iOS-iphone 13 pro when editing the picture a few times(just edit and save 2-3 times), image goes blank. The imageBase64 is missing, same as @zoranlj.
![image](https://github.com/scaleflex/filerobot-image-editor/assets/31616276/757acb41-5980-43f2-9c3e-0e139a67e79d)

**Closed** 2024-05-14 21:43 UTC
Labels: Released
