### ISSUE TITLE
Canvas CORS error on Firefox

### ISSUE THREAD

**Issue by dadepl** [scaleflex/filerobot-image-editor#242] opened 2022-08-02 11:38 UTC
Hi,

i'm getting error on script initialization on **Firefox**:

> Konva error: Unable to apply filter. The operation is insecure. This post my help you https://konvajs.org/docs/posts/Tainted_Canvas.html.

I'm using Vanilla JS approach and get latest JS from CDN - `https://scaleflex.cloudimg.io/v7/plugins/filerobot-image-editor/latest/filerobot-image-editor.min.js`
As mentioned in Konvajs link I have checked that `crossOrigin = Anonymous` is added in editor script - it is. Also my S3 from which I'm getting files to editor is responding with proper `Access-Control-Allow-Origin` header. And then I found that the problem that my Firefox has is order of assigning attributes to newly created image object. Part of code from above compressed JS:

`{return new Promise((function(n,r){var i=new Image;i.src=e,i.crossOrigin="Anonymous",i.name=null!=t?t:KI(e),i.onload=function(){n(i)},i.onerror=function(){r(new Error("Error in loading the image with the provided url: ".concat(e)))}}))}`

When I move this part:

`i.crossOrigin="Anonymous"`

before:

`i.src=e`

I have no error on Firefox:

`{return new Promise((function(n,r){var i=new Image;i.crossOrigin="Anonymous",i.src=e,i.name=null!=t?t:KI(e),i.onload=function(){n(i)},i.onerror=function(){r(new Error("Error in loading the image with the provided url: ".concat(e)))}}))}`

Does anyone else have such problem on Firefox? Could you please check and fix CDN JS if needed?

**Comment by GregoryPotdevin** [comment] 2022-09-30 12:24
We are currently seeing the same error using the CDN version, and it worked a few days ago when we implemented this code.
Using Chrome

**Comment by SaraZoarob** [comment] 2022-10-02 08:24
hello @dadepl, @GregoryPotdevin we will check and get back to you

**Comment by techistoner** [comment] 2022-12-05 04:42
remove  crossOrigin="Anonymous" image can display,but finetune fliters will be invalid ,any update?

**Comment by AhmeeedMostafa** [comment] 2023-02-10 18:27
The issue is fixed in version 4.3.8, please re-check it and let us know if all is good.

**Comment by rahulvramesh** [comment] 2023-04-16 03:59
same issue here

**Comment by AhmeeedMostafa** [comment] 2023-04-20 01:12
@ArturTovmasyan @rahulvramesh please post some more info? make sure ur server has "Access-Control-Allow-Origin" header in ur response?

**Closed** 2023-11-24 17:06 UTC
Labels: Released
