### ISSUE TITLE
Lossless save option

### ISSUE THREAD

**Issue by artemudovyk** [scaleflex/filerobot-image-editor#301] opened 2023-02-13 11:55 UTC
Hi!

I'm trying to save the image that I got from the backend, and even without applying any changes in the editor, there are noticeable differences in the input and output images in size and some loss in details on the images that the client wants to avoid:
![image](https://user-images.githubusercontent.com/58283675/218450846-617082e7-7abe-4006-b3eb-f01797d1873f.png)

Is it possible to save images without quality loss or any compression applied?

**Comment by AhmeeedMostafa** [comment] 2023-03-14 09:51
make sure that u don't have the `quality` option in the UI less than 92%, for some pics. 92% will be fine but for others should be 100% ... so make sure to always have the quality 100% to avoid such compression and let us know if u still face the issue after doing that

**Comment by artemudovyk** [comment] 2023-03-14 11:58
> make sure that u don't have the `quality` option in the UI less than 92%, for some pics. 92% will be fine but for others should be 100% ... so make sure to always have the quality 100% to avoid such compression and let us know if u still face the issue after doing that

Thanks. We actually don't use the default save method, and instead use a handler like this:
```javascript
const handleSave = async (editedImageObject: any, designState: any) => {
    // Init upload
    ...

    // Upload edited image
    await uploadBase64ImgAWSFormData(..., editedImageObject.imageBase64, ...);

    // Complete upload
    ...
  };
```

```javascript
<FilerobotImageEditor
  source={image.sourceUrl}
  onBeforeSave={() => false}
  onSave={handleSave}
  ...
/>
```

According to the docs `quality` parameter should not be applied here:
> NOTE: Quality modification will be applied to jpeg, jpg and webp types in returned [base64](https://github.com/scaleflex/filerobot-image-editor#onsave) format only while saving the image by the default behavior.

Or am I wrong here?

**Comment by AhmeeedMostafa** [comment] 2023-03-14 15:52
Yes u are right, but we still have another property that might change the resolution, please check it [`savingPixelRatio`](https://github.com/scaleflex/filerobot-image-editor#savingpixelratio)

**Comment by artemudovyk** [comment] 2023-03-14 17:01
At this moment it's set to:
```javascript
<FilerobotImageEditor
  ...
  savingPixelRatio={2}
  previewPixelRatio={2}
  ...
/>
```

If we increase it, the errors in Firefox (didn't test all browsers, but in Chrome it works) occur as in https://github.com/scaleflex/filerobot-image-editor/issues/172

We tried setting a higher value (even higher than the default `4`) for this and saving images in another browser, but the images are still lower quality than the originals.

**Comment by jjxtra** [comment] 2023-03-26 00:16
Also having this issue, anyone know any fix/workaround?

**Comment by AhmeeedMostafa** [comment] 2023-03-29 23:37
@all, a new property is added in v4.4.0 which is [`defaultSavedImageQuality`](https://github.com/scaleflex/filerobot-image-editor#defaultsavedimagequality) and it's used whether in default save behavior or custom after-saving implementation from ur side, if u need the highest resolution possible make it 1, it's by default 92

I think this will help u alot.

**Comment by jjxtra** [comment] 2023-03-29 23:50
Wonderful. How do we build a vanilla js version of 4.4.0?

**Comment by AhmeeedMostafa** [comment] 2023-03-30 00:10
@jjxtra it's already there, please check the installation in docs

**Comment by jjxtra** [comment] 2023-03-30 00:23
I built it successfully, integrated it into my project, set the default saved quality to 100, however I have the same issue where there is still significant loss of quality. Not sure what to check next. Posting my settings in case you see something that looks off.

```js
var { TABS, TOOLS } = FilerobotImageEditor;
var imgConfig =
{
    closeAfterSave: true,
    theme: st_is_dark ? filerobot_dark_theme : filerobot_light_theme,
    onBeforeSave: () => false,
    onSave: (editedImageObject, _) =>
    {
        // post editImageObject.imageBase64to api
    },
    annotationsCommon:
    {
        fill: '#ff0000'
    },
    defaultSavedImageType: 'webp',
    source: downloadLink,
    defaultSavedImageQuality: 1.0,
    tabsIds: [TABS.ADJUST, TABS.ANNOTATE, TABS.WATERMARK],
    defaultTabId: TABS.ANNOTATE, // or 'Annotate'
    defaultToolId: TOOLS.TEXT, // or 'Text'
    Text:
    {
        text: 'text',
        fontSize: 44
    }
};
imageEditor = new FilerobotImageEditor(imgElem, imgConfig);
imageEditor.render
({
    onClose: _ =>
    {
        imageEditor.terminate();
        imageEditor = null;
        _hide(imgElem);
    },
});
```

**Comment by jjxtra** [comment] 2023-03-30 00:27
Posting before and after image, all I did is add text. Load the first one in image editor. Then paste the second over the top you can see the significant blurring/quality loss.

Before:

![image](https://user-images.githubusercontent.com/1271832/228697224-48f5b1a1-a5bf-466e-98b0-cab66465ad00.png)

After:

![image](https://user-images.githubusercontent.com/1271832/228697243-09173482-4570-4a6e-bc66-0de5070cdb82.png)

**Comment by jjxtra** [comment] 2023-03-30 02:19
The demo here asks for a resolution upon saving, maybe that is the issue is that this is not defaulting to the original image size? https://scaleflex.github.io/filerobot-image-editor/

**Comment by AhmeeedMostafa** [comment] 2023-03-30 22:09
ur posted samples are not clear for me to show the issue of quality loss,
and after adding that new property and assigning it to 1, I don't see such quality loss in the generated image.... so could u please clarify this more how it happens & look after using the new property?

**Closed** 2024-05-14 21:52 UTC
Labels: question
