### ISSUE TITLE
Only few filters are applying like Invert, sepia and solarize.  

### ISSUE THREAD

**Issue by sanjota-vauntium** [scaleflex/filerobot-image-editor#266] opened 2022-10-10 15:36 UTC
I have applied filter like Moon, the code in the JSON is  filter: "Nb", This value is saving in the backend, but not applying back when i go back to edit the same updates.

Please help me to apply the saved filters back on the image in the editor.

This is the designState Object for the same

var designState = {
    "imgSrc": "https://thumbs.dreamstime.com/b/violet-purple-stars-gold-background-bokeh-texture-new-year-birthday-baby-shower-party-creative-pattern-banner-violet-133669452.jpg",
    "finetunes": [
        "Brighten"
    ],
    "finetunesProps": {
        "brightness": 0.2
    },
    "filter": "Nb",
    "adjustments": {
        "crop": {
            "ratio": "original",
            "ratioTitleKey": "original",
            "width": 569.95988,
            "height": 209.81648,
            "x": 0,
            "y": 0
        },
        "isFlippedX": false,
        "isFlippedY": false,
        "rotation": 0
    },
    "annotations": {
        "watermark": {
            "fill": "rgb(245, 50, 50)",
            "stroke": "#000000",
            "strokeWidth": 0,
            "shadowOffsetX": 0,
            "shadowOffsetY": 0,
            "shadowBlur": 0,
            "shadowColor": "#000000",
            "shadowOpacity": 1,
            "opacity": 1,
            "text": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
            "fontFamily": "Arial",
            "fonts": [
                {
                    "label": "Arial",
                    "value": "Arial"
                },
                "Tahoma",
                "Sans-serif",
                {
                    "label": "Comic Sans",
                    "value": "Comic-sans"
                }
            ],
            "fontSize": 24,
            "letterSpacing": 0,
            "lineHeight": 1,
            "align": "left",
            "fontStyle": "normal",
            "height": 104.90824,
            "width": 284.97994,
            "padding": 1,
            "x": 142.48997,
            "y": 52.45412,
            "id": "watermark",
            "name": "Text"
        }
    },
    "resize": {},
    "shownImageDimensions": {
        "width": 801.4295625,
        "height": 295.0262576953125,
        "scaledBy": 1
    }
}
const config = {
  source: designState.imgSrc,
  
  onSave: (editedImageObject, designState) =>{

//function to send the objects to server 
   jsonVal(editedImageObject,designState)
     
   //console.log('saved', editedImageObject, designState)
 },
 loadableDesignState: designState,
}

[ImageEditor.zip](https://github.com/scaleflex/filerobot-image-editor/files/9747220/ImageEditor.zip)

**Comment by AhmeeedMostafa** [comment] 2022-11-04 20:47
@sanjota-vauntium checked and issue produced, we will consider its fix in the upcoming releases and keep u updated once we have, thanks for reporting.

**Comment by AhmeeedMostafa** [comment] 2023-02-10 18:26
The issue is fixed in version 4.3.8, please re-check it and let us know if all is good.

**Closed** 2023-11-24 17:05 UTC
Labels: Released
