### ISSUE TITLE
Image random load success or failure by provide image url

### ISSUE THREAD

**Issue by jasstionzyf** [scaleflex/filerobot-image-editor#276] opened 2022-11-15 03:10 UTC
In react page, i provide the url to the image editor componment
Then click button to show the image editor, however some time it will failure to load the image  randomly just display nothing after loading icon disapper.
Also not any error logs.
The image request also is successfully.

**Comment by jasstionzyf** [comment] 2022-11-15 12:03
@AhmeeedMostafa  
https://watch.screencastify.com/v/ofAWgpaDIpwnAEHNrLJu

**Comment by AhmeeedMostafa** [comment] 2022-11-18 20:40
@jasstionzyf thanks for providing, we'll investigate it as it's hard to re-produce from our side and make sure it won't be included in the upcoming versions, thanks!

**Comment by ozgevsight** [comment] 2022-12-14 13:40
can you solve this problem as soon as possible ? This is a "image editor" but there is a problem displaying the image (randomly but it happens very often it shouldn't be that hard to catch) Thanks

**Comment by AhmeeedMostafa** [comment] 2023-02-09 22:56
It should be the same issue as this one (#251) but we will keep this duplicated issue for making sure it is not another issue after testing once we have the fix released.

**Comment by AhmeeedMostafa** [comment] 2023-02-10 18:25
The issue is fixed in version 4.3.8, please re-check it and let us know if all is good.

**Closed** 2023-04-16 15:30 UTC
Labels: Released
